# Generated by Django 5.2.4 on 2025-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='cartoons/')),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('genres', models.ManyToManyField(related_name='cartoons', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Мультфильм',
                'verbose_name_plural': 'Мультфильмы',
            },
        ),
    ]
