# Generated by Django 5.2.4 on 2025-09-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_cartoon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cartoon',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
