# Generated by Django 5.2.4 on 2025-09-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
